In [79]:
import numpy as np  
import pandas as pd

In [237]:
#importing Dataset
dataset = pd.read_excel(r'F:\Project\Machine Learning & Artificial Intelligence\Project 1-Major Depressive Disorder\Dataset\theta_power.xlsx')
dataset.head()

,ch1,ch2,ch3,ch4,ch5,ch6,ch7,ch8,ch9,ch10,ch11,ch12,ch13,ch14,ch15,ch16,ch17,ch18,ch19,classifier
0,0.010906,0.002175,0.002436,0.016596,0.985047,0.014885,0.985095,0.570675,0.997594,0.993385,0.016033,0.000635,0.000652,0.000000,0.999848,0.000000,0.999893,0.923586,0.995200,0
1,0.127685,0.000008,0.016913,0.141946,0.873930,0.126066,0.873901,0.549369,0.999803,0.916586,0.134360,0.000003,0.018219,0.159143,0.851791,0.148092,0.851760,0.920719,0.999725,0
2,0.187460,0.000049,0.075839,0.420153,0.618626,0.381340,0.618538,0.550006,0.982949,0.677226,0.400305,0.000007,0.030726,0.255841,0.761319,0.238600,0.761268,0.920747,0.999387,1
3,0.051082,0.000676,0.017867,0.081158,0.925342,0.074684,0.925341,0.557200,0.999914,0.958021,0.079794,0.000298,0.007267,0.052457,0.950902,0.049050,0.950913,0.922212,0.998008,0
4,0.282763,0.292443,0.818351,0.134387,0.618842,0.374328,0.625742,1.000000,0.237632,0.732982,0.400084,0.033376,0.548393,0.107351,0.744870,0.252839,0.747187,0.974434,0.571214,0

In [238]:
#seeing the charts
X=dataset.iloc[:,0:19]
X.head()

,ch1,ch2,ch3,ch4,ch5,ch6,ch7,ch8,ch9,ch10,ch11,ch12,ch13,ch14,ch15,ch16,ch17,ch18,ch19
0,0.010906,0.002175,0.002436,0.016596,0.985047,0.014885,0.985095,0.570675,0.997594,0.993385,0.016033,0.000635,0.000652,0.000000,0.999848,0.000000,0.999893,0.923586,0.995200
1,0.127685,0.000008,0.016913,0.141946,0.873930,0.126066,0.873901,0.549369,0.999803,0.916586,0.134360,0.000003,0.018219,0.159143,0.851791,0.148092,0.851760,0.920719,0.999725
2,0.187460,0.000049,0.075839,0.420153,0.618626,0.381340,0.618538,0.550006,0.982949,0.677226,0.400305,0.000007,0.030726,0.255841,0.761319,0.238600,0.761268,0.920747,0.999387
3,0.051082,0.000676,0.017867,0.081158,0.925342,0.074684,0.925341,0.557200,0.999914,0.958021,0.079794,0.000298,0.007267,0.052457,0.950902,0.049050,0.950913,0.922212,0.998008
4,0.282763,0.292443,0.818351,0.134387,0.618842,0.374328,0.625742,1.000000,0.237632,0.732982,0.400084,0.033376,0.548393,0.107351,0.744870,0.252839,0.747187,0.974434,0.571214

In [239]:
y=dataset.iloc[:,19]
y.head()

0    0
1    0
2    1
3    0
4    0
Name: classifier, dtype: int64

In [240]:
#splitting Dataset into train & test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [247]:
# Applying MLPNN Classifier
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(activation='relu',hidden_layer_sizes=(14,14,14,14,14),max_iter=1100,learning_rate='constant')
mlp.fit(X_train,y_train)
y_pred = mlp.predict(X_test)

In [248]:
y_pred

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [249]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[7, 0],
       [0, 5]], dtype=int64)

In [250]:
a=cm[0][0]
b=cm[0][1]
c=cm[1][0]
d=cm[1][1]
#calculation Error,Accuracy,Sensitivity and Prediction
Err=(b+c)/(a+b+c+d)
Acc=(a+d)/(a+b+c+d)
SN=a/(a+c)
Prec=a/(a+b)
print(cm)
print('Accuracy=',Acc*100,'%')
print('Error=',Err*100,'%')
print('Sensitivity=',SN*100,'%')
print('Prediction=',Prec*100,'%')

[[7 0]
 [0 5]]
Accuracy= 100.0 %
Error= 0.0 %
Sensitivity= 100.0 %
Prediction= 100.0 %