In [79]:
import numpy as np  
import pandas as pd

In [219]:
#importing Dataset
dataset = pd.read_excel(r'F:\Project\Machine Learning & Artificial Intelligence\Project 1-Major Depressive Disorder\Dataset\beta_power.xlsx')
dataset.head()

,ch1,ch2,ch3,ch4,ch5,ch6,ch7,ch8,ch9,ch10,ch11,ch12,ch13,ch14,ch15,ch16,ch17,ch18,ch19,classifier
0,0.997228,0.991636,0.020212,0.001879,0.001747,0.000000,1.000000,0.000000,1.000000,0.016227,0.998511,1.000000,0.000000,0.001275,0.002419,0.004084,0.995820,0.004137,0.995856,0
1,0.999394,0.891970,0.169635,0.000148,0.059648,0.281139,0.714566,0.285467,0.714428,0.001671,0.986836,0.783110,0.307584,0.000004,0.009764,0.074500,0.930654,0.069313,0.930645,0
2,0.994034,0.775770,0.307564,0.000152,0.049832,0.346803,0.655414,0.344628,0.655249,0.001720,0.990870,0.722645,0.369617,0.000011,0.026397,0.231222,0.785573,0.214449,0.785546,1
3,0.999399,0.959593,0.077738,0.010953,0.012614,0.046372,0.952440,0.047510,0.952477,0.071555,1.000000,0.974375,0.052124,0.000471,0.007039,0.030856,0.970550,0.029390,0.970560,0
4,0.399202,0.813232,0.320029,0.367169,0.911739,0.227204,0.489325,0.508607,0.491422,0.818887,0.114800,0.623185,0.540137,0.082965,0.387654,0.079419,0.826386,0.171542,0.828787,0

In [220]:
#seeing the charts
X=dataset.iloc[:,0:19]
X.head()

,ch1,ch2,ch3,ch4,ch5,ch6,ch7,ch8,ch9,ch10,ch11,ch12,ch13,ch14,ch15,ch16,ch17,ch18,ch19
0,0.997228,0.991636,0.020212,0.001879,0.001747,0.000000,1.000000,0.000000,1.000000,0.016227,0.998511,1.000000,0.000000,0.001275,0.002419,0.004084,0.995820,0.004137,0.995856
1,0.999394,0.891970,0.169635,0.000148,0.059648,0.281139,0.714566,0.285467,0.714428,0.001671,0.986836,0.783110,0.307584,0.000004,0.009764,0.074500,0.930654,0.069313,0.930645
2,0.994034,0.775770,0.307564,0.000152,0.049832,0.346803,0.655414,0.344628,0.655249,0.001720,0.990870,0.722645,0.369617,0.000011,0.026397,0.231222,0.785573,0.214449,0.785546
3,0.999399,0.959593,0.077738,0.010953,0.012614,0.046372,0.952440,0.047510,0.952477,0.071555,1.000000,0.974375,0.052124,0.000471,0.007039,0.030856,0.970550,0.029390,0.970560
4,0.399202,0.813232,0.320029,0.367169,0.911739,0.227204,0.489325,0.508607,0.491422,0.818887,0.114800,0.623185,0.540137,0.082965,0.387654,0.079419,0.826386,0.171542,0.828787

In [221]:
y=dataset.iloc[:,19]
y.head()

0    0
1    0
2    1
3    0
4    0
Name: classifier, dtype: int64

In [222]:
#splitting Dataset into train & test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [223]:
#applying KNN classifier
from sklearn.neighbors import KNeighborsClassifier

In [224]:
classifier=KNeighborsClassifier(n_neighbors=9)
classifier

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=9, p=2,
                     weights='uniform')

In [225]:
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [226]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[4, 3],
       [0, 5]], dtype=int64)

In [227]:
a=cm[0][0]
b=cm[0][1]
c=cm[1][0]
d=cm[1][1]
#calculation Error,Accuracy,Sensitivity and Prediction
Err=(b+c)/(a+b+c+d)
Acc=(a+d)/(a+b+c+d)
SN=a/(a+c)
Prec=a/(a+b)
print(cm)
print('Accuracy=',Acc*100,'%')
print('Error=',Err*100,'%')
print('Sensitivity=',SN*100,'%')
print('Prediction=',Prec*100,'%')

[[4 3]
 [0 5]]
Accuracy= 75.0 %
Error= 25.0 %
Sensitivity= 100.0 %
Prediction= 57.14285714285714 %